[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-visual-editor"

[template.environment]
  STACKBIT_API_KEY = "Add your Stackbit API key here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  framework = "#custom"
  port = 5173
  targetPort = 5173
  publish = "dist"
  autoLaunch = false

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]